### ISSUE TITLE
Not working with Console app?

### ISSUE THREAD

**Issue by jorisvdstraten** [egramtel/dotnet-bundle#11]
Hello!

Yesterday I tried to create a simple .net core 6 Console Hello World app on MacOS 12.1 (Monterey). The app itself is running fine, but when bundled into a package and running this app package, it quickly closes down after running.
I've made sure to add a Console.ReadLine() at the end.

**Comment by x2bool** [comment]
Hi! I am not sure how console apps supposed to work bundled into .app 

Is there a reason to bundle console apps at all? Why not just use executables?

**Comment by jorisvdstraten** [comment]
Thanks for your quick response! I want to distribute an asp.net selfhosted program. It does not necessarily need to be a console program, but I try to keep it as simple as possible.

**Comment by jorisvdstraten** [comment]
It works when using a minimal Avalon UI app.
